export const ADD_TODO = "ADD_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL = "COMPLETE_ALL";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_RECEIVED = "PROFILE_RECEIVED";

export const GET_SHAREPOINT_DATA = "GET_SHAREPOINT_DATA";
export const GET_REST_SHAREPOINT_DATA = "GET_REST_SHAREPOINT_DATA";

export const GET_SEARCHED_SHAREPOINT_DATA = "GET_SEARCHED_SHAREPOINT_DATA";
export const GET_USERSEARCHED_DATA = "GET_USERSEARCHED_DATA";

export const GET_GL_REPORT = "GET_GL_REPORT";

export const GET_CER_REPORT = "GET_CER_REPORT";

export const GET_CER_REPORT_FILTER = "GET_CER_REPORT_FILTER";

export const DASHBOARD_READY = "DASHBOARD_READY";

export const NEW_PTC = "NEW_PTC";
export const GET_PTC = "GET_PTC";
export const CHANGED_PTC = "CHANGED_PTC";

export const NEW_PTC_ITEM = "NEW_PTC_ITEM";
export const CHANGE_PTC_ITEM = "CHANGE_PTC_ITEM";
export const REMOVE_PTC_ITEM = "REMOVE_PTC_ITEM";

export const LOCALE_RECEIVED = "LOCALE_RECEIVED";

export const SWITCH_DEV_MODE = "SWITCH_DEV_MODE";

export const NEW_CA = "NEW_CA";
export const GET_CA = "GET_CA";
export const CHANGED_CA = "CHANGED_CA";
export const CHANGED_CA_RECORD = "CHANGED_CA_RECORD";

export const ADD_CA_ITEM = "ADD_CA_ITEM";
export const DELETE_CA_ITEM = "DELETE_CA_ITEM";
export const UPDATE_CA_ITEM = "UPDATE_CA_ITEM";

export const UPDATE_PTC_MASSUPLOAD = "UPDATE_PTC_MASSUPLOAD";
export const ADD_PTC_MASSUPLOAD_LOGS = "ADD_PTC_MASSUPLOAD_LOGS";

export const GET_PTC_MASSAPPROVE = 'GET_PTC_MASSAPPROVE'
