export const ADD_TODO = "ADD_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL = "COMPLETE_ALL";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_RECEIVED = "PROFILE_RECEIVED";

export const GET_SHAREPOINT_DATA = "GET_SHAREPOINT_DATA";
export const GET_REST_SHAREPOINT_DATA = "GET_REST_SHAREPOINT_DATA";

export const GET_SEARCHED_SHAREPOINT_DATA = "GET_SEARCHED_SHAREPOINT_DATA";
export const GET_USERSEARCHED_DATA = "GET_USERSEARCHED_DATA";
export const SWITCH_DEV_MODE = "SWITCH_DEV_MODE";

export const DASHBOARD_READY = 'DASHBOARD_READY';
export const CONTRACT_CHANGED = 'CONTRACT_CHANGED';

export const LOCALE_RECEIVED = "LOCALE_RECEIVED";